### ISSUE TITLE
What is the point of this library if you pass --add-opens to junit?

### ISSUE THREAD

**Issue by xxDark** [Rongmario/ImagineBreaker#3]
- fellow Jigsaw breaker

**Comment by Rongmario** [comment]
That's me being stupid and not knowing how to pass individual args to different tests.

**Comment by xxDark** [comment]
But the library doesn't work without these arguments?

**Comment by Rongmario** [comment]
The library enacts in 3 different ways:

1. Reflection <= needs `--add-opens=java.base/jdk.lang=ALL-UNNAMED`
2. Unsafe <= needs `--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED`
3. JNI <= doesn't need args

**Comment by xxDark** [comment]
👍
